# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c5983ec4ba7bea61ce080ed72e53c8efc55b959ec5a41937dcf6b27125c1e6b762ab3c432c3b701f92c4fffaf2908c9cceeffb9e95d1fed391dbf403a589b4e

test:
  secret_key_base: 0fb74af6f5faaa1b9a71601ef6d4d6e03e15a4434f58da685c14ed8eac9c8c6ce7bd3d26558fd5f1793616f515496818672ef7712c82fa68c91afabac3a2af72

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
